name: cape

on:
  push:
    branches:
      - master

env:
  osspath: ${{ secrets.OSSPATH }}
  endpoint: ${{ secrets.ENDPOINT }}
  access_key_id: ${{ secrets.ACCESS_KEY_ID }}
  access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
  bucket_name: ${{ secrets.BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14 stage
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.14.1
      - name: Use Go mod cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Checkout stage
        uses: actions/checkout@master
      - name: Run
        run: go run cape.go